### ISSUE TITLE
Stop run before creating more

### ISSUE THREAD

**Issue by normandy7** [neptune-ai/examples#134]
In Organize_ML_runs.ipynb, we encourage the user to create another run before stopping the first one. This will assign a new run to the `run` variable and the previously created run is left hanging.

https://github.com/neptune-ai/examples/blob/32c1e659a2f54f4372edd83f2e58308af1725f9f/how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb?short_path=3cf92bc#L266

Should we change the order here, or something else?

**Comment by SiddhantSadangi** [comment]
Thanks for raising this. #135 will fix this
