### ISSUE TITLE
Import statement

### ISSUE THREAD

**Issue by normandy7** [neptune-ai/examples#206]
https://github.com/neptune-ai/examples/blob/29473ccffb78ee5cdaa43f61160cd5352284ff51/integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb?short_path=3b753b3#L69

Should this be just `import neptune`, as the integration installs neptune-client `1.x`? (And same thing in the script)

**Comment by SiddhantSadangi** [comment]
Thanks!
Fixed in #207 .
