### ISSUE TITLE
 While providing API token to connect with my project getting error : The filename or extension is too long:

### ISSUE THREAD

**Issue by komal11lamba** [neptune-ai/examples#272]
{
	"name": "FileNotFoundError",
	"message": "[WinError 206] The filename or extension is too long: '.neptune\\\\async\\\\run__9a0540a5-6fa6-40c9-8a7a-9c6ed447ef85\\\\exec-1693473501.48087-2023-08-31_14.48.21.480870-20084\\\\upload_path'",
	"stack": "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m\n\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)\nCell \u001b[1;32mIn[8], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m run \u001b[39m=\u001b[39m neptune\u001b[39m.\u001b[39;49minit_run(\n\u001b[0;32m      2\u001b[0m     project\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39mmlteamdemo1/project-time-series-forecasting\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[0;32m      3\u001b[0m     api_token\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39meyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJhM2FkMTlhMi1iMTQ5LTRkZjktYTEyMS0zZGNmZDNjNTBlYzcifQ==\u001b[39;49m\u001b[39m\"\u001b[39;49m,\n\u001b[0;32m      4\u001b[0m ) \n\nFile \u001b[1;32md:\\cygnet\\NXLVL\\MyBackup_AzureML_Nxtlvl\\AIML_OutNetworkFeeds\\AIML\\lib\\site-packages\\neptune\\metadata_containers\\run.py:385\u001b[0m, in \u001b[0;36mRun.__init__\u001b[1;34m(self, with_id, project, api_token, custom_run_id, mode, name, description, tags, source_files, capture_stdout, capture_stderr, capture_hardware_metrics, fail_on_exception, monitoring_namespace, flush_period, proxies, capture_traceback, git_ref, dependencies, **kwargs)\u001b[0m\n\u001b[0;32m    382\u001b[0m \u001b[39mif\u001b[39;00m mode \u001b[39m==\u001b[39m Mode\u001b[39m.\u001b[39mOFFLINE \u001b[39mor\u001b[39;00m mode \u001b[39m==\u001b[39m Mode\u001b[39m.\u001b[39mDEBUG:\n\u001b[0;32m    383\u001b[0m     project \u001b[39m=\u001b[39m OFFLINE_PROJECT_QUALIFIED_NAME\n\u001b[1;32m--> 385\u001b[0m \u001b[39msuper\u001b[39;49m()\u001b[39m.\u001b[39;49m\u001b[39m__init__\u001b[39;49m(project\u001b[39m=\u001b[39;49mproject, api_token\u001b[39m=\u001b[39;49mapi_token, mode\u001b[39m=\u001b[39;49mmode, flush_period\u001b[39m=\u001b[39;49mflush_period, proxies\u001b[39m=\u001b[39;49mproxies)\n\nFile \u001b[1;32md:\\cygnet\\NXLVL\\MyBackup_AzureML_Nxtlvl\\AIML_OutNetworkFeeds\\AIML\\lib\\site-packages\\neptune\\metadata_containers\\metadata_container.py:132\u001b[0m, in \u001b[0;36mMetadataContainer.__init__\u001b[1;34m(self, project, api_token, mode, flush_period, proxies)\u001b[0m\n\u001b[0;32m    129\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_workspace: \u001b[39mstr\u001b[39m \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_api_object\u001b[39m.\u001b[39mworkspace\n\u001b[0;32m    130\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_project_name: \u001b[39mstr\u001b[39m \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_api_object\u001b[39m.\u001b[39mproject_name\n\u001b[1;32m--> 132\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_op_processor: OperationProcessor \u001b[39m=\u001b[39m get_operation_processor(\n\u001b[0;32m    133\u001b[0m     mode\u001b[39m=\u001b[39;49mmode,\n\u001b[0;32m    134\u001b[0m     container_id\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_id,\n\u001b[0;32m    135\u001b[0m     container_type\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mcontainer_type,\n\u001b[0;32m    136\u001b[0m     backend\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_backend,\n\u001b[0;32m    137\u001b[0m     lock\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_lock,\n\u001b[0;32m    138\u001b[0m     flush_period\u001b[39m=\u001b[39;49mflush_period,\n\u001b[0;32m    139\u001b[0m )\n\u001b[0;32m    140\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_bg_job: BackgroundJobList \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_prepare_background_jobs_if_non_read_only()\n\u001b[0;32m    141\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_structure: ContainerStructure[Attribute, NamespaceAttr] \u001b[39m=\u001b[39m ContainerStructure(NamespaceBuilder(\u001b[39mself\u001b[39m))\n\nFile \u001b[1;32md:\\cygnet\\NXLVL\\MyBackup_AzureML_Nxtlvl\\AIML_OutNetworkFeeds\\AIML\\lib\\site-packages\\neptune\\internal\\operation_processors\\factory.py:42\u001b[0m, in \u001b[0;36mget_operation_processor\u001b[1;34m(mode, container_id, container_type, backend, lock, flush_period)\u001b[0m\n\u001b[0;32m     33\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget_operation_processor\u001b[39m(\n\u001b[0;32m     34\u001b[0m     mode: Mode,\n\u001b[0;32m     35\u001b[0m     container_id: UniqueId,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     39\u001b[0m     flush_period: \u001b[39mfloat\u001b[39m,\n\u001b[0;32m     40\u001b[0m ) \u001b[39m-\u001b[39m\u001b[39m>\u001b[39m OperationProcessor:\n\u001b[0;32m     41\u001b[0m     \u001b[39mif\u001b[39;00m mode \u001b[39m==\u001b[39m Mode\u001b[39m.\u001b[39mASYNC:\n\u001b[1;32m---> 42\u001b[0m         \u001b[39mreturn\u001b[39;00m AsyncOperationProcessor(\n\u001b[0;32m     43\u001b[0m             container_id,\n\u001b[0;32m     44\u001b[0m             container_type,\n\u001b[0;32m     45\u001b[0m             backend,\n\u001b[0;32m     46\u001b[0m             lock,\n\u001b[0;32m     47\u001b[0m             sleep_time\u001b[39m=\u001b[39;49mflush_period,\n\u001b[0;32m     48\u001b[0m         )\n\u001b[0;32m     49\u001b[0m     \u001b[39melif\u001b[39;00m mode \u001b[39m==\u001b[39m Mode\u001b[39m.\u001b[39mSYNC:\n\u001b[0;32m     50\u001b[0m         \u001b[39mreturn\u001b[39;00m SyncOperationProcessor(container_id, container_type, backend)\n\nFile \u001b[1;32md:\\cygnet\\NXLVL\\MyBackup_AzureML_Nxtlvl\\AIML_OutNetworkFeeds\\AIML\\lib\\site-packages\\neptune\\internal\\operation_processors\\async_operation_processor.py:64\u001b[0m, in \u001b[0;36mAsyncOperationProcessor.__init__\u001b[1;34m(self, container_id, container_type, backend, lock, sleep_time, batch_size)\u001b[0m\n\u001b[0;32m     55\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m__init__\u001b[39m(\n\u001b[0;32m     56\u001b[0m     \u001b[39mself\u001b[39m,\n\u001b[0;32m     57\u001b[0m     container_id: UniqueId,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     62\u001b[0m     batch_size: \u001b[39mint\u001b[39m \u001b[39m=\u001b[39m \u001b[39m1000\u001b[39m,\n\u001b[0;32m     63\u001b[0m ):\n\u001b[1;32m---> 64\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_operation_storage \u001b[39m=\u001b[39m OperationStorage(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_init_data_path(container_id, container_type))\n\u001b[0;32m     66\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_queue \u001b[39m=\u001b[39m DiskQueue(\n\u001b[0;32m     67\u001b[0m         dir_path\u001b[39m=\u001b[39m\u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_operation_storage\u001b[39m.\u001b[39mdata_path,\n\u001b[0;32m     68\u001b[0m         to_dict\u001b[39m=\u001b[39m\u001b[39mlambda\u001b[39;00m x: x\u001b[39m.\u001b[39mto_dict(),\n\u001b[0;32m     69\u001b[0m         from_dict\u001b[39m=\u001b[39mOperation\u001b[39m.\u001b[39mfrom_dict,\n\u001b[0;32m     70\u001b[0m         lock\u001b[39m=\u001b[39mlock,\n\u001b[0;32m     71\u001b[0m     )\n\u001b[0;32m     73\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_container_id \u001b[39m=\u001b[39m container_id\n\nFile \u001b[1;32md:\\cygnet\\NXLVL\\MyBackup_AzureML_Nxtlvl\\AIML_OutNetworkFeeds\\AIML\\lib\\site-packages\\neptune\\internal\\operation_processors\\operation_storage.py:47\u001b[0m, in \u001b[0;36mOperationStorage.__init__\u001b[1;34m(self, data_path)\u001b[0m\n\u001b[0;32m     44\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_data_path \u001b[39m=\u001b[39m data_path\u001b[39m.\u001b[39mresolve()\n\u001b[0;32m     46\u001b[0m \u001b[39m# initialize directory\u001b[39;00m\n\u001b[1;32m---> 47\u001b[0m os\u001b[39m.\u001b[39;49mmakedirs(data_path \u001b[39m/\u001b[39;49m OperationStorage\u001b[39m.\u001b[39;49mUPLOAD_PATH, exist_ok\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m)\n\nFile \u001b[1;32mC:\\ProgramData\\Miniconda\\lib\\os.py:225\u001b[0m, in \u001b[0;36mmakedirs\u001b[1;34m(name, mode, exist_ok)\u001b[0m\n\u001b[0;32m    223\u001b[0m         \u001b[39mreturn\u001b[39;00m\n\u001b[0;32m    224\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 225\u001b[0m     mkdir(name, mode)\n\u001b[0;32m    226\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mOSError\u001b[39;00m:\n\u001b[0;32m    227\u001b[0m     \u001b[39m# Cannot rely on checking for EEXIST, since the operating system\u001b[39;00m\n\u001b[0;32m    228\u001b[0m     \u001b[39m# could give priority to other errors like EACCES or EROFS\u001b[39;00m\n\u001b[0;32m    229\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m exist_ok \u001b[39mor\u001b[39;00m \u001b[39mnot\u001b[39;00m path\u001b[39m.\u001b[39misdir(name):\n\n\u001b[1;31mFileNotFoundError\u001b[0m: [WinError 206] The filename or extension is too long: '.neptune\\\\async\\\\run__9a0540a5-6fa6-40c9-8a7a-9c6ed447ef85\\\\exec-1693473501.48087-2023-08-31_14.48.21.480870-20084\\\\upload_path'"
}

**Comment by SiddhantSadangi** [comment]
Hello @komal11lamba 👋 

Thank you for reporting this issue! Could you please provide us with more details:

**1.  Reproduction**
﻿﻿In as much detail as possible, please provide steps to reproduce the issue or code snippet.﻿
﻿﻿
**2. Traceback**
Add formatted traceback or log output/screenshots to help explain your problem.﻿

**3. Environment info**﻿
The output of `pip list`:
﻿The operating system you're using:
﻿﻿The output of `python --version`:
﻿﻿
﻿﻿﻿﻿**4. Additional context**
﻿﻿﻿﻿﻿Add any other context about the problem here.
