### ISSUE TITLE
Missing None Check in wandb Exporter

### ISSUE THREAD

**Issue by stefan-baumann** [neptune-ai/examples#345]
Hi, in https://github.com/neptune-ai/examples/blob/8ef274c49addea2ef74fd8184dbb847d8195baa7/utils/migration_tools/from_wandb/wandb_to_neptune.py#L48 you try to access an environment variable to fill in a default, but then call `.split()` on the returned value even if it's None, causing an exception.

**Comment by SiddhantSadangi** [comment]
Hey @stefan-baumann 👋 
Thanks a lot for bringing this to my attention.

I've fixed this now. Can you check and let me know if it works for you? 🤗
