### ISSUE TITLE
Neptune_catalyst.ipynb fails

### ISSUE THREAD

**Issue by jakubczakon** [neptune-ai/examples#42]
Seems that the Neptune_catalyst.ipynb is failing. 
Perhaps there is some type as it seems to be missing the `run` object. 
https://github.com/neptune-ai/examples/runs/2932574924?check_suite_focus=true

**Comment by kamil-kaczmarek** [comment]
on it.

**Comment by kamil-kaczmarek** [comment]
#43 fixing here

**Comment by kamil-kaczmarek** [comment]
fixed in #43
